

CREATE DATABASE SQL_PROJECT;

USE SQL_PROJECT;

CREATE TABLE EMPLOYEE_DETAIL_TABLE
(
EMPLOYEE_ID INT PRIMARY KEY,
FIRST_NAME CHAR(255),
LAST_NAME CHAR(255),
SALARY MONEY,
JOINING_DATE DATETIME NOT NULL,
DEPARTMENT CHAR(255),
GENDER CHAR(255)
)


INSERT INTO EMPLOYEE_DETAIL_TABLE VALUES
(1, 'vikas', 'ahlawat', 600000, '2/12/2013 11:16', 'IT', 'MALE'),
(2, 'nikita', 'jain', 530000, '2/14/2013 11:16', 'HR', 'FEMALE'),
(3, 'ashish', 'kumar', 1000000, '2/14/2013 11:16', 'IT', 'MALE'),
(4, 'nikhil', 'sharma', 480000, '2/15/2013 11:16', 'HR', 'MALE'),
(5, 'anish', 'kadian', 500000, '2/16/2013 11:16', 'PAROLL', 'MALE')


 SELECT * FROM EMPLOYEE_DETAIL_TABLE

 SELECT FIRST_NAME FROM EMPLOYEE_DETAIL_TABLE

 SELECT UPPER(FIRST_NAME) FROM EMPLOYEE_DETAIL_TABLE

 SELECT UPPER(LAST_NAME) FROM EMPLOYEE_DETAIL_TABLE

 SELECT CONCAT(FIRST_NAME , ' ' ,LAST_NAME) AS NAME FROM EMPLOYEE_DETAIL_TABLE

 SELECT * FROM EMPLOYEE_DETAIL_TABLE
   WHERE FIRST_NAME = 'vikas'
   
 SELECT * FROM EMPLOYEE_DETAIL_TABLE
   WHERE FIRST_NAME like 'a%'

 SELECT * FROM EMPLOYEE_DETAIL_TABLE
   WHERE LAST_NAME like 'a%'

 SELECT * FROM EMPLOYEE_DETAIL_TABLE
   WHERE FIRST_NAME like '%h'

 SELECT * FROM EMPLOYEE_DETAIL_TABLE
   WHERE FIRST_NAME like '[a-p]%'

 SELECT * FROM EMPLOYEE_DETAIL_TABLE
   WHERE FIRST_NAME not like '[a-p]%'

 SELECT * FROM EMPLOYEE_DETAIL_TABLE
   WHERE GENDER like '__LE'

 SELECT * FROM EMPLOYEE_DETAIL_TABLE
   WHERE FIRST_NAME like 'a____'

 SELECT * FROM EMPLOYEE_DETAIL_TABLE
   WHERE FIRST_NAME like '%[%]%'
   -----EMPTY BECAUSE WE DONT HAVE Vik%as LIKE THIS IN OUR TABLE-----

 SELECT DISTINCT(DEPARTMENT) FROM  EMPLOYEE_DETAIL_TABLE

 SELECT MAX(SALARY) FROM EMPLOYEE_DETAIL_TABLE

 SELECT MIN(SALARY) FROM EMPLOYEE_DETAIL_TABLE

 SELECT CONVERT(VARCHAR,JOINING_DATE,106) FROM EMPLOYEE_DETAIL_TABLE

 SELECT CONVERT(VARCHAR,JOINING_DATE,111) FROM EMPLOYEE_DETAIL_TABLE

 SELECT CONVERT(VARCHAR,JOINING_DATE,108) FROM EMPLOYEE_DETAIL_TABLE
 
 SELECT YEAR(JOINING_DATE)  FROM EMPLOYEE_DETAIL_TABLE

 SELECT MONTH(JOINING_DATE)  FROM EMPLOYEE_DETAIL_TABLE
 
 SELECT GETDATE() 

 SELECT GETUTCDATE()

 SELECT FIRST_NAME, GETDATE() AS CURRENTDATE, JOINING_DATE FROM EMPLOYEE_DETAIL_TABLE
    SELECT DATEDIFF(MONTH,'2013/02/12', '2024/02/22' ) FROM EMPLOYEE_DETAIL_TABLE

 SELECT FIRST_NAME, GETDATE() AS CURRENTDATE, JOINING_DATE FROM EMPLOYEE_DETAIL_TABLE
    SELECT DATEDIFF(DAY,'2013/02/12', '2024/02/22' ) FROM EMPLOYEE_DETAIL_TABLE

 SELECT *FROM EMPLOYEE_DETAIL_TABLE
    WHERE YEAR(JOINING_DATE) = 2013 

 SELECT *FROM EMPLOYEE_DETAIL_TABLE
    WHERE MONTH(JOINING_DATE) = 1 

 SELECT *FROM EMPLOYEE_DETAIL_TABLE
    WHERE MONTH(JOINING_DATE) = 1 

	SELECT COUNT(*) FROM EMPLOYEE_DETAIL_TABLE

 SELECT TOP 1 * FROM EMPLOYEE_DETAIL_TABLE

 SELECT * FROM EMPLOYEE_DETAIL_TABLE
    WHERE FIRST_NAME IN ('vikas', 'ashish', 'nikhil')

 SELECT * FROM EMPLOYEE_DETAIL_TABLE
    WHERE FIRST_NAME NOT IN ('vikas', 'ashish', 'nikhil')

 SELECT RTRIM(FIRST_NAME) AS [FirstName] FROM EMPLOYEE_DETAIL_TABLE

  SELECT LTRIM(FIRST_NAME) AS [FirstName] FROM EMPLOYEE_DETAIL_TABLE

 SELECT FIRST_NAME,CASE 
    WHEN Gender ='Male' THEN 'M'
    WHEN Gender ='Female' THEN 'F'
    END AS [Gender]
    FROM EMPLOYEE_DETAIL_TABLE

 SELECT 'Hello'+ ' '  +  FIRST_NAME FROM EMPLOYEE_DETAIL_TABLE

 SELECT * FROM EMPLOYEE_DETAIL_TABLE
    WHERE SALARY > 600000

 SELECT * FROM EMPLOYEE_DETAIL_TABLE
    WHERE SALARY < 700000

 SELECT * FROM EMPLOYEE_DETAIL_TABLE
    WHERE SALARY BETWEEN 500000 AND 600000
---------------------------------------------------------------
CREATE TABLE PRODUCT_DETAIL_TABLE
(
ProductDetail_ID INT,
EmployeeDetail_ID INT,
Project_Name VARCHAR(255),
)

INSERT INTO PRODUCT_DETAIL_TABLE VALUES
(1, 1, 'Task Track'),
(2,1, 'CLP'),
(3, 1, 'Survey Managment'),
(4, 2, 'HR Managment'),
(5,3, 'Task Track'),
(6,3, 'GRS'),
(7,3, 'DDS'),
(8,4, 'HR Managment'),
(9,6, 'GL Managment')

 SELECT * FROM PRODUCT_DETAIL_TABLE
 
 SELECT DEPARTMENT,SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEE_DETAIL_TABLE
    GROUP BY DEPARTMENT

 SELECT DEPARTMENT,SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEE_DETAIL_TABLE
    GROUP BY DEPARTMENT ORDER BY SUM(SALARY) ASC

 SELECT DEPARTMENT,SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEE_DETAIL_TABLE
    GROUP BY DEPARTMENT ORDER BY SUM(SALARY) DESC

 SELECT DEPARTMENT, COUNT(*) AS TOTAL_DEPARTMENT ,SUM(SALARY) AS TOTAL__SALARY FROM EMPLOYEE_DETAIL_TABLE
    GROUP BY DEPARTMENT
 
 SELECT DEPARTMENT, AVG(SALARY) AS AVERAGE_SALARY FROM EMPLOYEE_DETAIL_TABLE
    GROUP BY DEPARTMENT ORDER BY AVG(SALARY) ASC

 SELECT DEPARTMENT, MAX(SALARY) AS MAXIMUM_SALARY FROM EMPLOYEE_DETAIL_TABLE
    GROUP BY DEPARTMENT ORDER BY MAX(SALARY) ASC

 SELECT DEPARTMENT, MIN(SALARY) AS MINIMUM_SALARY FROM EMPLOYEE_DETAIL_TABLE
    GROUP BY DEPARTMENT ORDER BY MIN(SALARY) ASC

 SELECT DEPARTMENT, MIN(SALARY) AS MINIMUM_SALARY FROM EMPLOYEE_DETAIL_TABLE
    GROUP BY DEPARTMENT ORDER BY MIN(SALARY) ASC

 SELECT *  FROM EMPLOYEE_DETAIL_TABLE 
    INNER JOIN 
    PRODUCT_DETAIL_TABLE 
    ON 
    EMPLOYEE_DETAIL_TABLE.EMPLOYEE_ID  = PRODUCT_DETAIL_TABLE.EmployeeDetail_ID

 SELECT FIRST_NAME, PROJECT_NAME FROM EMPLOYEE_DETAIL_TABLE  
    INNER JOIN 
	PRODUCT_DETAIL_TABLE 
    ON
	EMPLOYEE_ID = EmployeeDetail_ID
    ORDER BY FIRST_NAME
 
 SELECT FIRST_NAME, PROJECT_NAME FROM EMPLOYEE_DETAIL_TABLE  
    LEFT OUTER JOIN 
	PRODUCT_DETAIL_TABLE 
    ON
	EMPLOYEE_ID = EmployeeDetail_ID
    ORDER BY FIRST_NAME

 SELECT FIRST_NAME,ISNULL(PROJECT_NAME,'No Project Assigned') as PROJECT_NAMES FROM EMPLOYEE_DETAIL_TABLE 
    LEFT OUTER JOIN
    PRODUCT_DETAIL_TABLE  
    ON
	EMPLOYEE_ID = EmployeeDetail_ID ORDER BY FIRST_NAME

	
 SELECT FIRST_NAME, PROJECT_NAME FROM EMPLOYEE_DETAIL_TABLE  
    RIGHT OUTER JOIN 
    PRODUCT_DETAIL_TABLE  
    ON
	EMPLOYEE_ID = EmployeeDetail_ID ORDER BY FIRST_NAME

 SELECT FIRST_NAME, PROJECT_NAME FROM EMPLOYEE_DETAIL_TABLE FULL
    OUTER JOIN
    PRODUCT_DETAIL_TABLE 
    ON 
	EMPLOYEE_ID = EmployeeDetail_ID ORDER BY FIRST_NAME

 SELECT FIRST_NAME, PROJECT_NAME FROM EMPLOYEE_DETAIL_TABLE FULL
    OUTER JOIN
    PRODUCT_DETAIL_TABLE 
    ON 
	EMPLOYEE_ID = EmployeeDetail_ID ORDER BY FIRST_NAME

 SELECT FIRST_NAME, PROJECT_NAME FROM EMPLOYEE_DETAIL_TABLE FULL
    OUTER JOIN
    PRODUCT_DETAIL_TABLE 
    ON 
	EMPLOYEE_ID = EmployeeDetail_ID ORDER BY FIRST_NAME

 
SELECT EMPLOYEE_ID, FIRST_NAME, PROJECT_NAME FROM EMPLOYEE_DETAIL_TABLE 
    INNER JOIN PRODUCT_DETAIL_TABLE 
    ON EMPLOYEE_DETAIL_TABLE.EMPLOYEE_ID = PRODUCT_DETAIL_TABLE.EmployeeDetail_ID
    WHERE EMPLOYEE_ID IN 
	( SELECT EmployeeDetail_ID FROM PRODUCT_DETAIL_TABLE
      GROUP BY EmployeeDetail_ID 
	  HAVING COUNT(EmployeeDetail_ID) >1 )


 SELECT FIRST_NAME, PROJECT_NAME FROM EMPLOYEE_DETAIL_TABLE  
    INNER JOIN PRODUCT_DETAIL_TABLE 
    ON EMPLOYEE_ID = EmployeeDetail_ID 

 SELECT * FROM EMPLOYEE_DETAIL_TABLE
    CROSS JOIN 
	PRODUCT_DETAIL_TABLE
	